# Teste encoder
gcc -Wall -o ./build/test_encoder ../src/encoder.cpp test_encoder.cpp -lpigpio -lrt -lm -lpthread -lstdc++ -lraspicam -lrf24-bcm -I../include

# Teste roda
#gcc -Wall -o ./build/test_wheel ../src/dc_motor.cpp ../src/encoder.cpp ../src/wheel.cpp test_wheel.cpp -lpigpio -lrt -lm -lpthread -lstdc++ -lraspicam -lrf24-bcm -I../include

# Teste radio
#gcc -Wall -o ./build/test_nrf24l01 test_nrf24l01.cpp -lpigpio -lrt -lm -lpthread -lstdc++ -lraspicam -lrf24-bcm -I../include

# Teste detector de item
#gcc -Wall -o ./build/test_item_detector ../src/item_detector.cpp test_item_detector.cpp -lpigpio -lrt -lm -lpthread -lstdc++ -lraspicam -lrf24-bcm -I../include

# Teste trava
#gcc -Wall -o ./build/test_lock ../src/servo.cpp ../src/lock.cpp test_lock.cpp -lpigpio -lrt -lm -lpthread -lstdc++ -lraspicam -lrf24-bcm -I../include

# Teste camera opencv
#gcc -Wall -o ./build/test_camera_opencv test_camera_opencv.cpp -lpigpio -lrt -lm -lpthread -lstdc++ -lraspicam -lraspicam_cv -lrf24-bcm \
# -lopencv_core -lopencv_highgui -lopencv_imgcodecs \
# -I../include -I/usr/local/include -I/usr/local/include/opencv4

# Teste pid
#gcc -Wall -o ../test/build/test_control ../src/dc_motor.cpp ../src/encoder.cpp ../src/wheel.cpp ./movement.cpp test_control.cpp ./pid/pid.cpp -lpigpio -lrt -lm -lpthread -lstdc++ -lraspicam -lrf24-bcm -I../include -I./ -I./pid
